// src/components/hiForm/renders/RenderRadio.vue
<template>
  <a-radio-group
    v-model:value="formData[controller.model]"
    :options="radioChildren"
    :style="style"
    @change="onChange"
  />
</template>

<script setup lang="ts">
import { HiFormRadioController } from '@/components/hiForm/controller/hiFormRadioController'
import type { PropType } from 'vue'
import type { TFormData } from '@/components/hiForm/types'

const props = defineProps({
  controller: {
    type: HiFormRadioController,
    required: true
  },
  formData: {
    type: Object as PropType<TFormData>,
    required: true
  }
})

const { controller, formData } = props
const config = controller?.getConfig()
const { onChange, children, style } = config
const radioChildren =
  children && 'getChildren' in children ? children.getChildren() : children || []
</script>

<style scoped></style>

// src/components/hiForm/renders/renderRadio.tsx
import type { HiFormRadioController } from '@/components/hiForm/controller/hiFormRadioController'
import type { TFormData } from '@/components/hiForm/types'

interface IRenderRadioProps {
  controller: HiFormRadioController
  formData: TFormData
}

const renderRadio = ({ controller, formData }: IRenderRadioProps) => {
  const config = controller.getConfig()
  const { children, onChange } = config

  const radioChildren =
    children && 'getChildren' in children ? children.getChildren() : children || []

  return (
    <a-radio-group
      v-model:value={formData[controller.model]}
      options={radioChildren}
      onChange={onChange}
    />
  )
}

export default renderRadio
